### Get all categories
GET http://localhost:3000/api/categories
X-API-Key: SECRET
Accept: application/json

### Create a category
POST http://localhost:3000/api/categories
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Handphone"
}

### Get category by Id
GET http://localhost:3000/api/categories/100
X-API-Key: SECRET
Accept: application/json

### Update category by Id
PUT http://localhost:3000/api/categories/2
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

### Delete category by Id
DELETE http://localhost:3000/api/categories/1
X-API-Key: SECRET
Accept: application/json